import { FileText, LayoutList, Target, HelpCircle, Download } from 'lucide-react';
import './DocumentViewer.css';

export default function DocumentViewer({ document }) {
  const handleDownload = () => {
    const reqs = document.requirements.length > 0 ? document.requirements.map((r, i) => `${i + 1}. ${r}`).join('\n') : "None yet.";
    const ucs = document.useCases.length > 0 ? document.useCases.map((u, i) => `${i + 1}. ${u}`).join('\n') : "None yet.";
    
    const content = `# Business Requirements Document: ${document.projectTitle}\n\n## Requirements\n${reqs}\n\n## Use Cases\n${ucs}\n\n---\n*Generated by BA Agent*`;
    
    const blob = new Blob([content], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const a = window.document.createElement('a');
    a.href = url;
    a.download = `${document.projectTitle.replace(/\\s+/g, '_').toLowerCase()}_report.md`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="glass-panel document-pane fade-in-up" style={{ animationDelay: '0.1s' }}>
      <div className="header" style={{ justifyContent: 'space-between' }}>
        <div style={{ display: 'flex', alignItems: 'center', gap: '0.75rem' }}>
          <FileText size={22} color="var(--accent-color)" />
          <h2>Live Business Requirements Document</h2>
        </div>
        <button onClick={handleDownload} className="download-btn" title="Download Markdown Report">
          <Download size={18} />
        </button>
      </div>
      
      <div className="document-content">
        <div className="doc-section title-section">
          <h3>Project: {document.projectTitle}</h3>
          <p className="doc-meta">Last updated: Just now • Version 0.1 draft</p>
          
          {/* Detail Score Indicator */}
          <div className="detail-indicator-container fade-in-up">
            <div className="detail-header">
              <span className="detail-label">Requirements Depth:</span>
              <span className="detail-status" style={{ color: document.detailScore >= 80 ? '#22c55e' : '#eab308' }}>
                {document.detailScore >= 80 ? 'Detailed Enough' : 'Requires More Detail'} ({document.detailScore || 0}%)
              </span>
            </div>
            <div className="progress-bar-bg">
              <div 
                className="progress-bar-fill" 
                style={{ 
                  width: `${document.detailScore || 0}%`, 
                  background: (document.detailScore || 0) >= 80 ? '#22c55e' : ((document.detailScore || 0) >= 50 ? '#eab308' : '#ef4444') 
                }}
              ></div>
            </div>
          </div>
        </div>

        <div className="doc-section">
          <div className="section-header">
            <Target size={18} />
            <h3>Business Requirements</h3>
          </div>
          {document.requirements.length === 0 ? (
            <div className="empty-state">No requirements identified yet. Chat with the agent to start building.</div>
          ) : (
            <ul className="req-list">
              {document.requirements.map((req, i) => (
                <li key={i} className="animate-fade-in" style={{ animationDelay: `${i * 0.05}s` }}>
                  {req}
                </li>
              ))}
            </ul>
          )}
        </div>

        <div className="doc-section">
          <div className="section-header">
            <LayoutList size={18} />
            <h3>Use Cases</h3>
          </div>
          {document.useCases.length === 0 ? (
            <div className="empty-state">No use cases generated yet.</div>
          ) : (
            <div className="use-case-list">
              {document.useCases.map((uc, i) => (
                <div key={i} className="use-case-card animate-fade-in" style={{ animationDelay: `${i * 0.05}s` }}>
                  <h4>Use Case {i + 1}</h4>
                  <p>{uc}</p>
                </div>
              ))}
            </div>
          )}
        </div>

        {document.clarifyingQuestions && document.clarifyingQuestions.length > 0 && (
          <div className="doc-section compact-questions fade-in-up">
            <div className="section-header">
              <HelpCircle size={16} color="#eab308" />
              <h3 style={{ fontSize: '1rem', color: '#eab308', margin: 0 }}>Clarification Needed</h3>
            </div>
            <ul className="compact-q-list">
              {document.clarifyingQuestions.map((q, i) => (
                <li key={i} className="animate-fade-in" style={{ animationDelay: `${i * 0.05}s` }}>
                  {q}
                </li>
              ))}
            </ul>
          </div>
        )}
      </div>
    </div>
  );
}
