import pdfMake from "pdfmake/build/pdfmake";
import pdfFonts from "pdfmake/build/vfs_fonts";

// Bind virtual file system for fonts safely
pdfMake.vfs = (pdfFonts && pdfFonts.pdfMake) ? pdfFonts.pdfMake.vfs : pdfFonts.vfs;

export function generatePDFReport(docData) {
  const content = [
    { text: 'Business Requirements Document', style: 'header' },
    { text: `Project: ${docData.projectTitle || 'Untitled'}`, style: 'subHeader' },
    { text: `Generated by BA Agent on ${new Date().toLocaleDateString()}`, style: 'meta', margin: [0, 0, 0, 20] }
  ];

  // Actors Section
  if (docData.actors && docData.actors.length > 0) {
    content.push({ text: 'Identified Actors', style: 'sectionHeader' });
    content.push({ ul: docData.actors, margin: [0, 0, 0, 20] });
  }

  // Requirements Section
  if (docData.requirements && docData.requirements.length > 0) {
    content.push({ text: 'Business Requirements', style: 'sectionHeader' });
    
    const reqsList = docData.requirements.map(req => {
      return { text: req, margin: [0, 0, 0, 4] };
    });
    
    content.push({ ul: reqsList, margin: [0, 0, 0, 20] });
  } else {
    content.push({ text: 'Business Requirements', style: 'sectionHeader' });
    content.push({ text: 'No requirements identified.', margin: [0, 0, 0, 20], italics: true });
  }

  // Use Cases Section
  if (docData.useCases && docData.useCases.length > 0) {
    content.push({ text: 'Use Cases', style: 'sectionHeader' });
    
    docData.useCases.forEach((uc, index) => {
      if (typeof uc === 'string') {
        content.push({ text: `${index + 1}. ${uc}`, style: 'useCaseTitle', margin: [0, 10, 0, 5] });
      } else {
        content.push({ text: `${index + 1}. ${uc.title || 'Untitled'}`, style: 'useCaseTitle', margin: [0, 15, 0, 8] });
        
        if (uc.description) {
          content.push({ text: [{ text: 'Description: ', bold: true }, uc.description], margin: [10, 0, 0, 8] });
        }
        
        if (uc.preconditions && uc.preconditions.length > 0) {
          content.push({ text: 'Preconditions:', bold: true, margin: [10, 0, 0, 4] });
          content.push({ ul: uc.preconditions, margin: [25, 0, 0, 8] });
        }
        
        if (uc.postconditions && uc.postconditions.length > 0) {
          content.push({ text: 'Postconditions:', bold: true, margin: [10, 0, 0, 4] });
          content.push({ ul: uc.postconditions, margin: [25, 0, 0, 8] });
        }
        
        if (uc.scenarios && uc.scenarios.length > 0) {
          content.push({ text: 'Scenarios:', bold: true, margin: [10, 0, 0, 4] });
          // Strip native LLM numbering to use pdfMake ordered list naturally
          const cleanScenarios = uc.scenarios.map(s => s.replace(/^[\\d\\.\\)]+\\s*/, ''));
          content.push({ ol: cleanScenarios, margin: [25, 0, 0, 15] });
        } else {
          content.push({ text: '', margin: [0, 0, 0, 10] }); // spacing
        }
      }
    });
  } else {
    content.push({ text: 'Use Cases', style: 'sectionHeader' });
    content.push({ text: 'No use cases identified.', margin: [0, 0, 0, 20], italics: true });
  }

  const docDefinition = {
    content: content,
    pageMargins: [50, 50, 50, 50],
    styles: {
      header: {
        fontSize: 24,
        bold: true,
        color: '#1e293b',
        margin: [0, 0, 0, 8]
      },
      subHeader: {
        fontSize: 16,
        bold: true,
        color: '#4f46e5',
        margin: [0, 0, 0, 4]
      },
      meta: {
        fontSize: 10,
        italics: true,
        color: '#64748b'
      },
      sectionHeader: {
        fontSize: 18,
        bold: true,
        color: '#0f172a',
        background: '#f1f5f9',
        margin: [0, 15, 0, 10]
      },
      useCaseTitle: {
        fontSize: 14,
        bold: true,
        color: '#1e293b',
        decoration: 'underline'
      }
    },
    defaultStyle: {
      fontSize: 11,
      color: '#334155',
      lineHeight: 1.4
    }
  };

  const safeFileName = `${(docData.projectTitle || 'Untitled').replace(/\\s+/g, '_')}_BRD.pdf`;
  pdfMake.createPdf(docDefinition).download(safeFileName);
}
